### PR TITLE
fix: raised the starboard threshold

### PR DESCRIPTION
**Pull request by KommentatorForAll**

### CODE REVIEW

**Comment by Chicken** [comment]
Maybe make it even larger, like 400

**Comment by KommentatorForAll** [comment]
> Maybe make it even larger, like 400

Rather 300. it should be okish hard to push to starboard. i think it is enough that 3 people give their crystal

**Comment by Chicken** [comment]
A single person can give 275 worth of star points

**Review by Chicken — APPROVED** [review]

**Comment by CiramorDev** [comment]
for me a message in starboard should at least have a amount of points equivalent to 4 tier 5 crystals, I don't know how much that represents in points but it seems legit to me

**Review by WilsontheWolf — APPROVED** [review]

**Pull request merged**
